/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        //create the binary tree
        BinaryTree binaryTree= new BinaryTree();

        //Adds nodes to the tree
        binaryTree.setRoot(new Node(300));
        binaryTree.getRoot().setLeft(new Node(2));
        binaryTree.getRoot().setRight(new Node(3));
        binaryTree.getRoot().getLeft().setLeft(new Node(4));
        binaryTree.getRoot().getLeft().setRight(new Node (67));
        binaryTree.getRoot().getLeft().setLeft(new Node(50));
        binaryTree.getRoot().getLeft().setRight(new Node(200));
        binaryTree.getRoot().getRight().setLeft(new Node(150));
        binaryTree.getRoot().getRight().setRight(new Node(90));


        System.out.println("inorder");
        binaryTree.inOrderTraverse(binaryTree.getRoot());
        System.out.println(" ");
        System.out.println("postOrder");
        binaryTree.postOrderTraverse(binaryTree.getRoot());

        System.out.println(" ");
        System.out.println("preOrder");
        binaryTree.preOrderTraverse(binaryTree.getRoot());

        BinarySearchTree binarySearchTree= new BinarySearchTree();
        binarySearchTree.add(5);
        binarySearchTree.add(7);
        binarySearchTree.add(3);
        binarySearchTree.add(10);

        System.out.println(" ");
        System.out.println(binarySearchTree.containsNode(10));
        System.out.println(binarySearchTree.containsNode(5));
        System.out.println(binarySearchTree.containsNode(100));

        System.out.println("Max Node is : " + binaryTree.findMax(binaryTree.getRoot()));

    }
}
