/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {

    public static void main(String[] args) {

       Stack<java.io.Serializable> stack= new Stack<>();

       stack.push(111);
        stack.push(222);
        stack.push(333);
        stack.push(444);

        System.out.println(stack.toString());

        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.peek());

        System.out.println(stack.toString());

        System.out.println(stack.isEmpty());

//        Queue<java.io.Serializable> queue=new Queue<>();
//        queue.enqueue(111);
//        queue.enqueue(222);
//        queue.enqueue(333);
//        queue.enqueue(444);
//        System.out.println(queue.toString());

//        System.out.println(queue.dequeue());
//        System.out.println(queue.dequeue());
//
//        System.out.println(queue.peek());
//        System.out.println(queue.isEmpty());

//        System.out.println(queue.toString());
    }
}
