/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BLOG;


public class App {
    public static void main(String[] args) {
     int arr[]= {8,4,23,42,16,15};
        sortArr(arr);
    }

    public static void sortArr(int[] arr){
           int n = arr.length;

        for (int i = 0; i <n; i++) {
            int min = i;
            for (int j = i+1; j < n; j++) {
                if(arr[j]< arr[min]){
                    min=j;
                }
            }
            int temp = arr [min];
            arr[min]= arr[i];
            arr[i]= temp;
            System.out.println(arr[i]);
            }

        }
}
