/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BLOG;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
     int arr[]= {8,4,23,42,16,15};
        sortArr(arr);
    }

    public static ArrayList sortArr(int[] arr){
           int n = arr.length;
        ArrayList<Integer> sortedArr= new ArrayList<>();
        for (int i = 0; i <n-1 ; i++) {
            int min = i;
            for (int j = i+1; j < n; j++) {
                if(arr[j]< arr[min]){
                    min=j;
                }
            }
            int temp = arr [min];
            arr[min]= arr[i];
            arr[i]= temp;
            sortedArr.add(arr[i]);
        }
        System.out.println(sortedArr);
       return sortedArr;
    }
}
