/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {

    public static void main(String[] args) {
        HashTable<String, String> studentAllowences = new HashTable<>();

//        studentAllowences.add("aaa", 300);
//        studentAllowences.add("bbb", 400);
//        studentAllowences.add("kkkk", 3510);
//        studentAllowences.add("jjjj", 3004);
//
//        System.out.println(" the size is => "+ studentAllowences.getSize());
//        System.out.println( studentAllowences.get("aaa"));
//        System.out.println( studentAllowences.get("kkkk"));
//        System.out.println( studentAllowences.contain("kkkk"));
//        System.out.println( studentAllowences.contain("sss"));
//
//        System.out.println(studentAllowences.remove("aaa"));
//        System.out.println(" the size is => "+ studentAllowences.getSize());

//        String input = "Once upon a time, there was a brave princess who...";
//        String input = "Taco cat ate a taco";
//        System.out.println(studentAllowences.firstRepeated(input));

        HashTable<String, String> first = new HashTable<>();
        HashTable<String, String> second = new HashTable<>();

        first.add("fond","enamored");
        first.add("wrath","anger");
        first.add("guide","usher");

        second.add("fond","averse");
        second.add("wrath","delight");
        second.add("guide","follow");

        System.out.println(studentAllowences.leftJoin(first,second));
    }
}
